include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    argument_type_not_assignable: ignore
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
  exclude:
    - lib/generated/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    #- custom_lint
    - dart_code_linter
linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_js_rounded_ints
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_returning_this
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - conditional_uri_does_not_exist
    - discarded_futures
    - do_not_use_environment
    - eol_at_end_of_file
    - implicit_call_tearoffs
    - implicit_reopen
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - literal_only_boolean_expressions
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_default_cases
    - no_literal_bool_comparisons
    - no_runtimeType_toString
    - no_self_assignments
    - noop_primitive_operations
    - omit_local_variable_types
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_foreach
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_void_to_null
    - prefer_single_quotes
    - require_trailing_commas
    - secure_pubspec_urls
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - sort_pub_dependencies
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_to_list_in_spreads
    - unnecessary_null_checks
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unsafe_html
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
    - use_super_parameters
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_to_and_as_if_applicable
    - use_test_throws_matchers

custom_lint:
  rules:
    - always_specify_parameter_names
    - avoid_dynamic
    - avoid_inverted_boolean_expressions
    - avoid_mutable_global_variables
    - avoid_positional_fields_in_records
    - avoid_redundant_pattern_field_names
    - avoid_unused_parameters:
      ignored_parameters: ['ctx', 'context']
    - boolean_prefixes
    - no_duplicate_imports
    - no_self_comparisons
    - prefer_async_await
    - prefer_const_constructor_declarations
    - prefer_immediate_return
    - prefer_iterable_any
    - prefer_iterable_first
    - prefer_iterable_last
    - prefer_library_prefixes
    - prefer_underscore_for_unused_callback_parameters
    - unnecessary_nullable_return_type
    # Flutter
    - avoid_public_members_in_states
    - avoid_single_child_in_flex
    - dispose_controllers
    - prefer_async_callback
    - prefer_border_from_border_side
    - prefer_border_radius_all
    - prefer_dedicated_media_query_functions
    - prefer_text_rich
    - prefer_void_callback
    - proper_edge_insets_constructors
    - proper_from_environment
    - proper_super_dispose
    - proper_super_init_state
    - use_spacer

dart_code_linter:
  rules:
    - arguments-ordering:
        child-last: true
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-non-null-assertion
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - member-ordering:
        alphabetize: true
        order:
          - named-constructors
          - factory-constructors
          - private-final-fields
          - private-fields
          - private-late-final-fields
          - private-late-fields
          - private-nullable-fields
          - public-final-fields
          - public-fields
          - public-late-final-fields
          - public-late-fields
          - public-nullable-fields
          - private-getters-setters
          - public-getters-setters
          - overridden-methods
          - private-methods
          - public-methods
          - public-static-methods
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-immediate-return
    - prefer-iterable-of
    # Flutter
    - avoid-border-all
    - avoid-expanded-as-spacer
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - prefer-correct-edge-insets-constructor
    - prefer-using-list-view
    - use-setstate-synchronously