include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**.g.dart
  plugins:
    - custom_lint
linter:
  rules:
    prefer_single_quotes: true