name: flutterfly
description: A flutter template.

publish_to: 'none'

version: 1.5.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.2.2
  dio: ^5.5.0
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  fl_query: ^1.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  fpdart: ^1.1.0
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.2
  niku: ^2.4.3
  retrofit: ^4.1.0
  watch_it: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.11
  change_app_package_name: ^1.2.0
  custom_lint: ^0.6.4
  dart_mappable_builder: ^4.2.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  import_sorter: ^4.6.0
  injectable_generator: ^2.6.1
  mocktail: ^1.0.4
  pyramid_lint: ^2.0.0
  remove_from_coverage: ^2.0.0
  retrofit_generator: ^8.1.1
  source_gen: ^1.5.0

import_sorter:
  comments: false

flutter:
  uses-material-design: true

  assets:
    - assets/
