name: flutterfly
description: A flutter template.

publish_to: 'none'

version: 1.4.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  cupertino_icons: ^1.0.5
  dio: ^5.3.0
  fluent_ui: ^4.7.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  fpdart: ^0.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  niku: ^2.4.2
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0
  tailwind_colors : ^0.3.1

dependency_overrides:
  custom_lint: 0.5.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.0
  flutter_lints: ^2.0.2
  freezed: ^2.4.1
  icons_launcher: ^2.1.3
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: AminaReska
      fonts:
        - asset: assets/fonts/amina-reska.ttf
    - family: FuturaPTMedium
      fonts:
      - asset: assets/fonts/FuturaPTMedium.otf