name: flutterfly
description: A flutter template.

publish_to: 'none'

version: 1.5.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  fpdart: ^1.1.0
  json_annotation: ^4.8.1
  niku: ^2.4.2
  riverpod_annotation: ^2.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.3
  icons_launcher: ^2.1.4
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
