name: flutterfly
description: A flutter template.

publish_to: 'none'

version: 1.5.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.2
  fpdart: ^1.1.0
  json_annotation: ^4.8.1
  niku: ^2.4.2
  riverpod_annotation: ^2.1.6
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.3
  icons_launcher: ^2.1.4
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0-dev.2
  riverpod_lint: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/
