name: flutterfly
description: A flutter template.

publish_to: 'none'

version: 1.2.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  fluent_ui: ^4.6.2
  flutter_riverpod: ^2.3.6
  fpdart: ^0.6.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  nester: ^1.2.1
  niku: ^2.3.3
  riverpod_context: ^0.3.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  icons_launcher: ^2.1.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
