name: flutterfly
description: A flutter template.

publish_to: 'none'

version: 1.1.1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  fluent_ui: ^4.1.5
  flutter_riverpod: ^2.1.3
  fpdart: ^0.4.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  nester: ^1.2.1
  niku: ^2.3.3
  riverpod_context: ^0.3.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  icons_launcher: ^2.0.6
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
