name: flutterfly
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.0.1
  fluent_ui: ^3.12.0
  flutter_native_splash: ^2.2.3+1
  http: ^0.13.4
  json_annotation: ^4.5.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0

flutter_native_splash:
  color: "#2196F3"
  image: assets/statical.png
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: AminaReska
      fonts:
        - asset: assets/fonts/amina-reska.ttf
    - family: FuturaPTMedium
      fonts:
      - asset: assets/fonts/FuturaPTMedium.otf