name: flutterfly
description: A flutter template.

publish_to: 'none'

version: 1.4.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  fluent_ui: ^4.8.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  niku:
    git:
      url: https://github.com/victor7w7r/niku.git
      ref: main
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  icons_launcher: ^2.1.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: AminaReska
      fonts:
        - asset: assets/fonts/amina-reska.ttf
    - family: FuturaPTMedium
      fonts:
      - asset: assets/fonts/FuturaPTMedium.otf