name: flutterfly
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  http: ^0.13.4
  flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#2196F3"
  image: assets/statical.png
  android: true

flutter:
  uses-material-design: true
    
  assets:
    - assets/
