name: "Github Deploy"
env:
  my_secret: ${{secrets.commit_secret}}
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: "Enabling Flutter for Web"
        run: flutter config --enable-web
      - name: "Install dependencies"
        run: flutter pub get
      - name: "Enable for Publishing"
        run: |
          rm web/index.html
          mv web/index.prod.html web/index.html
      - name: "Compiling..."
        run: flutter build web --web-renderer canvaskit
      - name: "Deploying..."
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web